require 'pact/provider/proxy/tasks'
require 'pact/provider_verifier/json_helper'

# make sure that the required environment variables are sets
required_environment_variables = ['pact_urls', 'provider_base_url']
missing_environment_variables = required_environment_variables.select { |ev| ENV[ev].to_s == '' }
if missing_environment_variables.count > 0 then
  raise("ERROR: the following environment variables have not been specified: '#{missing_environment_variables}'")
end

# Non-mandatory, but probably useful environment variables
other_environment_variables = ['provider_states_url', 'provider_states_setup_url']
missing_environment_variables = other_environment_variables.select { |ev| ENV[ev].to_s == '' }
if missing_environment_variables.count > 0 then
  warn("WARN: the following non-mandatory environment variables have not been specified: '#{missing_environment_variables}'")
end

pacts = ENV['pact_urls'].split(',')
# if you have duplicates in the pact_urls you will see more iterations than expected,
# but that shouldn't be the case except when you're trying stuff out in dev

def get_pact_consumer_name pact_url
    json = get_json(pact_url)
    json['consumer']['name']
end

task :verify_pacts do
    pacts.each do |pact_url|
        Pact::ProxyVerificationTask.new :"#{pact_url}" do | task |
            ENV['pact_consumer'] = get_pact_consumer_name(pact_url)
            task.pact_url pact_url, :pact_helper => './pact_helper'
            task.provider_base_url ENV['provider_base_url']
        end
        task_name = "pact:verify:#{pact_url}"
        Rake::Task[task_name].invoke
        Rake::Task[task_name].reenable
    end
end
