FROM ruby:3.4.10-alpine@sha256:6acf053b0254716d793f1e72030742f1b3bf665fd343aed3df15d3e449d06b76

RUN apk update \
    && apk --no-cache add \
      "build-base" \
      "bash" \
      "ca-certificates" \
      "git" \
      "tzdata" \
    && rm -rf /var/cache/apk/*

WORKDIR /app

COPY Gemfile pact-provider-verifier.gemspec /app/
COPY lib/pact/provider_verifier/version.rb /app/lib/pact/provider_verifier/version.rb

RUN gem install bundler -v '2.5.23' \
    && bundle install --jobs 3 --retry 3

CMD []
