FROM ruby:3.4.11-alpine@sha256:50133d02799e7da49a1e0bd16d865701622fd61d150a8cd3463edf0016504af5

RUN apk update \
    && apk --no-cache add \
      "build-base" \
      "bash" \
      "ca-certificates" \
      "git" \
      "tzdata" \
    && rm -rf /var/cache/apk/*

WORKDIR /app

COPY Gemfile pact-provider-verifier.gemspec /app/
COPY lib/pact/provider_verifier/version.rb /app/lib/pact/provider_verifier/version.rb

RUN gem install bundler -v '2.5.23' \
    && bundle install --jobs 3 --retry 3

CMD []
